src/components/Graph.js
This PR intorduce graph reloading in OpenRCA UI. After user choose proper data, the request to MockAPI is processed and based on the data in response new graph is generated.
I manage to obtain solution, where there is calculating comparison between previous and next state (nodes, links etc.) during graph update. Only new objects are generated - rest of them is inherited from previous state. Thus in our case the animation will look very smooth  :sunglasses:
=> Adding graph reloading

package.json, src/assets/ui.css, src/components/DateTimePicker.js, src/components/Graph.js, yarn.lock
This PR resolves #30 and introducing graph filtering by namespace.
User will have a possibility to choose any namespace that occurs nodes information. To use it with ``mock-api`` #39 need to be resolved. Filtering is performed on the client side. In the test scenario I divided current ``mock-api`` payload to 2 namespaces based on the node index (``even`` and ``odd``). You can see a behaviour in following GIF.
Payload without ``properties.namespace`` key is supported still as before.
=> Graph filtering by namespace

package.json, src/assets/ui.css, src/components/Graph.js, yarn.lock
This PR is related to #22. Graph scaling and centering features were added.
The main difficulty is due to the fact that our graph is force directed tree. During simulation it dynamically changes shape, width and height. Scale and center operations base on this features. Thus it is hard to find the right moment for which these operations should trigger automatically. After tests in my environment I come to conclusion that proper value estimates about 2 seconds and I used it in this changes.
In my opinion it would be great to provide some button in UI which could trigger rescaling operation. User could easily adapt shape of his graph to available space.
I also think that initial seconds of operations could be hidden behind loader component. After some time (e.g. mentioned 2 seconds) …
=> Add scale graph feature

src/components/NodeDetailCard.js, src/components/NodeDetailCard.scss, src/components/_variables.scss
The Node Detail Card displays information such as node coordinates and other irrelevant information. This PR changes this behavior so only `properties` are displayed (without `name` field). `name` field is displayed as a subtitle below `kind`. 
Here's how it looks:
Hopefully `properties` will be extended with more information in near future.
=> Show only relevant information in card

src/components/Graph.js
This PR introducing adding alert nodes in proper namespace after filtering.
Refers to #53.
=> Add alerts nodes to proper namespace

src/components/Graph.js, src/components/Graph.scss, src/components/NodeDetailCard.scss
This PR resolves #37 and introducing graph statistics. I reused Detail Card to display number of different types of components.
These changes should be compatible with #54 after merging. If you have any comments and ideas how to improve UI please share them!
=> Display graph statistics

package.json, src/components/DateTimePicker.js, src/components/Graph.js, src/components/Graph.scss, src/components/IconMap.js, src/components/_variables.scss, src/index.js, yarn.lock
This PR introduces node icons:
Now  #5 should finally be closable.
The impact on graph display performance should not be too noticeable.
Screen captures:
=> Add node icons

src/components/Alerts.js, src/components/Alerts.scss, src/components/index.js
This PR resolves #72 by adding a stylization to alerts table. Width of the table is dynamic relative to a user browser width. There were also minor fixes with using uppercase or capital letter in some field in the table. I temporary extended a payload for a better visualization (e.g. pager). 
There is still some unresolved issues, like hovering color in select menu or color of calendar icon, but so for I didn't find an easy solution so far. We can try to use this version, collect some issues and provide resolving it in another PR.
=> Customize alerts table

src/components/DateTimePicker.js, src/components/Graph.js
This PR limit default view to ``cluster``, ``node``, ``pod`` and ``alert`` objects.
=> Cluster, node, pod and alert as default type

src/components/Graph.js
This PR closes #91, by function order redefinition in first graph generating in orca-ui.
The problem was connected with ``scaleGraph()`` function, which we triggered 2 seconds after page load. Sometimes it occurred that there wasn't time enough to get response from backend server and apply it to graph definition. This PR makes, that timeout starts **after** getting a response.
Moreover if there is a situation that ``scaleGraph()`` function was triggered and no nodes were detected in the graph, transform operation isn't executed.
=> Attribute transform large graph error

Dockerfile, README.md, nginx.conf.tpl, utils/docker-compose.yaml, utils/orca_proxy/nginx.conf
The default port has been changed from 80 to 8080 to avoid requirement for elevated privileges in some cases.
The port is now configurable via environment variable `LISTEN_PORT`. The `README.md` was updated accordingly.
Example:
``` sh
docker run -it --rm\
--name orca-ui \
--network=host \
-e "LISTEN_PORT=8555" \
-e "BACKEND_URL=http://127.0.0.1:5000" \
openrca/orca-ui
```
This PR should close #108
=> Configurable port for Orca UI

src/components/Graph.js
This PR resolves #114. Alert nodes are filtered after type filtering.
=> Filter alert nodes after type filtering

Dockerfile, utils/Dockerfile
Time of subsequent builds has been reduced by 50% for production `Dockerfile` and even more for development one as shown in table below.
`Dockerfile` | first build | second build (after source code change)
--- | --- | ---
production |   113.78 | 63.88
development |  74.26 |  9.00
Without proposed changes second build would take around the same as the first one. 
This should close #115
=> Optimize build time of UI images.

src/components/Graph.js
This PR remove old circles and text (icon too!) elements remaining after graph reloading. This PR will solve #117 and optimize simulation.
=> Remove old circle and text elements

src/components/NodeDetailCard.scss
* Table height is now limited
* Scrollbar appears if table is big enough
This should close #121 
Screenshot:
=> Set maximum height of the table

package.json, src/components/Graph.js, src/components/NodeDetailCard.js, src/components/NodeDetailCard.scss, yarn.lock
This PR introduce new Detail Card view. In this new approach we wanted to display nodes details using some collapsable JSON format, instead of table view, which was really unreadable for more complexes objects.
Details of a pod:
Statistics:
As you can see, apart from clear, readable, flexible and easily to navigate view we provide a lot of useful features for operators, like:
- number of items in an array/ objects
- items type
- copy to clipboard option
I decided to set the collapse parameter to 2nd degree of nesting in default view.
=> Detail card modification

src/components/Graph.js
This PR resolves bug described in #134 and #135. ``classed()`` func should not be executed on empty data.
=> Remove classed func execution on empty data

src/components/Graph.js
In some cases nodes object doesn't have namespace assigned. It happens in case of ``nodes``, ``clusters``, ``alerts`` etc. The previous behavior didn't included that fact in constructing namespaces list, and in that case the ``undefined`` namespace was pushed to the list. It occured as an empty namespace option in namespace selector described in #133. This PR resolves that issue by filtering undesirable values from namespace option list.
=> Empty namespace

src/components/RCA.js, src/components/Visualization.js
This PR provide d3 graph in RCA dashboard. By default the first structure provided in ``/rca`` endpoint is generated in the dashboard. As in ``/graph`` dashboard, graph component covers whole possible area.
The demo with mocked data provided in separate [branch](https://github.com/openrca/orca-ui/tree/rca_graph_mock). Provided changes in this PR requires new endpoint in RCA backend.
=> Add RCA Graph

src/components/Graph.scss, src/components/RCA.js
This PR introduces link labels in RCA dashboards containing trajectory strength. Label orientation to be determined -> status WIP.
=> Add link labels in rca dashboard

src/components/NodeDetailCard.js, src/components/NodeDetailCard.scss, src/components/RCA.js
This PR introduces NodeDetailCard component in RCA dashboard.
=> Add node detail card in RCA graph

src/components/Graph.js
This PR resolves #181. There is added parsing to integer type of a timestamp value.
=> Cast timestamp to integer
