- CONTRIBUTING.md
- LICENSE
- README.md
* License
* README
* Badges
* Contribution guide
> Community stuff

- utils/orca_mock/.gitignore
- utils/orca_mock/Dockerfile
- utils/orca_mock/MANIFEST.in
- utils/orca_mock/README.md
- utils/orca_mock/orca_mock/__init__.py
- utils/orca_mock/orca_mock/api/__init__.py
- utils/orca_mock/orca_mock/api/resources/__init__.py
- utils/orca_mock/orca_mock/api/resources/v1/__init__.py
- utils/orca_mock/orca_mock/api/resources/v1/graph.py
- utils/orca_mock/orca_mock/app.py
- utils/orca_mock/orca_mock/cmd/api.py
- utils/orca_mock/orca_mock/exceptions.py
- utils/orca_mock/requirements.txt
- utils/orca_mock/setup.py
- utils/orca_mock/test-requirements.txt
- utils/orca_mock/tox.ini
> Graph API mock

- .dockerignore
- Dockerfile
- README.md
This PR introduce ``Dockerfile`` for OpenRCA UI app (#9) and ``README.md`` adjustment.
> Dockerize UI

- utils/README.md
- utils/docker-compose.yaml
Update utils readme with instructions. Resolves #12
> Add docker-compose.yaml for development

- src/assets/ui.css
- src/components/Graph.js
This PR introduces following changes in graph navigation (described in #18):
- graph box expansion
- enabling drag and drop option
- graph panning
- graph zooming
> Improve graph navigation

- utils/orca_mock/orca_mock/app.py
- utils/orca_mock/requirements.txt
It implements (#34)
Signed-off-by: Aleksandra Galara <a.galara@samsung.com>
> Add CORS headers

- public/index.html
This simply PR closes #36 through updating browser title.
> Update browser title

- package.json
- src/assets/ui.css
- src/components/DateTimePicker.js
- src/index.js
- yarn.lock
This PR closes #40 by introducing reload button placed next to date time picker. So far using button triggers same action as picker, in future will be requesting for the most actual data.
> Adding reload button

- src/components/_variables.scss
> Change default margin for DatePicker component

- src/assets/ui.css
- src/components/Alerts.js
- src/components/Graph.scss
- src/components/NodeDetailCard.scss
- src/components/_variables.scss
Applies the dark color scheme to all UI components.
Closes #50.
> Dark UI mode

- src/components/DateTimePicker.js
- src/components/DateTimePicker.scss
- src/components/Graph.js
- src/components/_variables.scss
I've tweaked the bottom navbar a bit and, as a bonus, changed the STATS button so it is more visible:
_Here be screenshots:_
namespace selection:
I have not yet changed the appearance of the calendar though.
Oh yes, the related issue is #68
> Change styling of bottom navbar to fit with the rest of the app (#68)

- src/components/DateTimePicker.js
- src/components/DateTimePicker.scss
- src/components/Graph.js
This PR resolves #66 by introducing multi selector by object type.
> Object type multi selector

- src/components/Graph.js
This resolves #74 by including cluster and proper nodes object in namespace view.
> Display cluster and proper nodes objects in namespace view 

- src/components/DateTimePicker.js
- src/components/Graph.js
> Use timestamp param in graph endpoint

- src/components/Alerts.js
- utils/orca_mock/orca_mock/mock_data/alerts.json
* Updates mocked alerts payload with real data.
* Fixes alerts root in API request.
Closes #86.
> Fix alerts root

- src/components/Graph.js
Adjusts graph force parameters. Improves visualization clarity and spacing:
Closes #75.
> Adjust graph force

- package.json
- src/components/Graph.js
- src/components/NodeDetailCard.js
- src/components/NodeDetailCard.scss
- yarn.lock
This PR closes #70 and #71. Please have a look on detail card now :)
> Render a table in detail card, switch type and name atributes

- src/components/Navbar.js
- src/components/Navbar.scss
> Add alerts count badge

- src/components/Graph.js
- src/components/Graph.scss
Resolves #107. Calculating and coloring fault trajectory in a graph.
> Calculate and color fault trajectory

- src/components/Graph.js
- src/components/Graph.scss
* Added colored outline/background to node
* Made hovered node raise to the top so it is not covered by other elements
This should close #113 if you guys like the result. Let me know if this approach is acceptable.
*Here be screenshots*
> Make hovered node label stand out

- src/components/Alerts.js
- src/components/Graph.js
- src/components/Navbar.js
This PR introduces lint fixes to meet CI requirements.
> Lint fixes

- src/assets/_variables.scss
- src/components/Graph.js
Every time data is fetched from API, the operation is indicated by rotation of refresh icon (bottom left corner).
There is no screenshot because it wouldn't capture the movement :)
This should close #144
> Indicate graph refresh

- package.json
- src/components/RCA.js
- src/components/index.js
- src/index.js
- yarn.lock
This is initial commit of RCA dashboard provided in OpenRCA UI.
Root Cause Analysis algorithm requires an initial object to perform analysis. The idea is to provide a comfortable way to enter the dashboard and start the calculation. The proper alert ``id`` will be passed to the subpage via query params. The way to construct link and redirect to subpage will be detailed implemented in following weeks.
So far the dashboard contains the most required logic to provide possibility to parallel programming. The PR contains routing, initializing a component state and performing an example of the request. Components like fault trajectory graph, rca output table etc will be provided in next PRs.
> RCA dashboard introduction

- src/components/DateTimePicker.scss
Here are some style tweaks to datetime picker. Hopefully it will blend better into the whole UI. 
Suggestions are welcome :) I am not so sure about border color. There is also distinct color for keyboard selection that might be a bit too different from mouse selection color - let me know what you think.
Here are some pictures:
Here we have date selected, date hovered with mouse pointer and date selected using keyboard all at the same time:
This should close #142 when finished
> Style date time picker

- package.json
- src/components/Item.js
- src/components/Item.scss
- src/components/NodeDetailCard.scss
- src/components/RCA.js
- src/components/Selector.js
- yarn.lock
This PR resolves PR by introducing basic fault trajectory selector. The main functionality is to choose one of provided fault trajectory, ordered by probability of occurrence. After selecting on of available item, the graph is reloaded with new trajectory. Thera are some still thigs todo, like styling selector box, or change general width and style of selector component. This features will be provided in separate PR.
> Add fault trajectory selector

- src/components/Graph.scss
- src/components/RCA.js
This PR introduce links arrows in rca dashboard
> Add links arrows
